repos:
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry-check
        description: run poetry check to validate scheduler project config
        entry: poetry check
        language: python
        language_version: python3.10
        pass_filenames: false
        files: ^pyproject.toml$

      - id: poetry-lock
        name: poetry-lock
        description: run poetry lock to update lock file
        entry: poetry lock
        language: python
        language_version: python3.10
        pass_filenames: false
        files: ^(poetry.lock|pyproject.toml)$

      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: poetry run ruff
        language: system
        types: [ python ]
        require_serial: true

      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff' for extremely fast Python formatting"
        entry: poetry run ruff --fix
        language: system
        types: [ python ]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]